DROP TABLE IF EXISTS taches;
CREATE TABLE taches (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    nom TEXT NOT NULL,
    description TEXT NOT NULL,
);
